language: node_js

node_js:
  - 8

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
    - yarn install
    - yarn run build-css

cache:
  yarn: true

env:
  global:
    - NODE_PATH: src/
    - BLOCKCYPHER_TOKEN: 539e6971dd0342ba988e3e4bc609c809
    - secure: BCgb4M88zB0Bx0v47MpVMd36Yz5KlXmkXpUy7ZbYZcnGH9JvxA3dqURl1uXlwZ+XAPHw2hawQ9YblrTrL5Z7SaI8VbghTe/ML9cS5MV7dYB3XzlkP7ga6GcJ6RYB25ak3DWc+ax4V1t/bpLylBBxK9yh9IZ1SPPJ56z9MRyZh7DjrJMvuZtRYJk75EvQOw5Umkxhjig649JYSFV4aRYTTP4MYDzrZ2fmynpk4/TfOPzpqTjfvNT7KCi2wQ85X/z+XHT1CdswOMxMrffsHLIYTegSaBORaygEau8SOMG+87aSDdbDrwv/lip06mvcz1mdT8ZQaMGBnury9Ah2QGjkWw==
